// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (typeof Backbone !== "undefined" && Backbone !== null) {
    this.DiscussionModuleView = (function(_super) {
      __extends(DiscussionModuleView, _super);

      function DiscussionModuleView() {
        this.navigateToPage = __bind(this.navigateToPage, this);
        this.renderPagination = __bind(this.renderPagination, this);
        this.addThread = __bind(this.addThread, this);
        this.renderDiscussion = __bind(this.renderDiscussion, this);
        this.loadPage = __bind(this.loadPage, this);
        _ref = DiscussionModuleView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      DiscussionModuleView.prototype.events = {
        "click .discussion-show": "toggleDiscussion",
        "click .new-post-btn": "toggleNewPost",
        "click .new-post-cancel": "hideNewPost",
        "click .discussion-paginator a": "navigateToPage"
      };

      DiscussionModuleView.prototype.paginationTemplate = function() {
        return DiscussionUtil.getTemplate("_pagination");
      };

      DiscussionModuleView.prototype.page_re = /\?discussion_page=(\d+)/;

      DiscussionModuleView.prototype.initialize = function() {
        var match;
        this.toggleDiscussionBtn = this.$(".discussion-show");
        match = this.page_re.exec(window.location.href);
        if (match) {
          return this.page = parseInt(match[1]);
        } else {
          return this.page = 1;
        }
      };

      DiscussionModuleView.prototype.toggleNewPost = function(event) {
        event.preventDefault();
        if (!this.newPostForm) {
          this.toggleDiscussion();
          this.isWaitingOnNewPost = true;
          return;
        }
        if (this.showed) {
          this.newPostForm.slideDown(300);
        } else {
          this.newPostForm.show();
        }
        this.toggleDiscussionBtn.addClass('shown');
        this.toggleDiscussionBtn.find('.button-text').html("Hide Discussion");
        this.$("section.discussion").slideDown();
        return this.showed = true;
      };

      DiscussionModuleView.prototype.hideNewPost = function(event) {
        event.preventDefault();
        return this.newPostForm.slideUp(300);
      };

      DiscussionModuleView.prototype.toggleDiscussion = function(event) {
        var $elem;
        if (this.showed) {
          this.$("section.discussion").slideUp();
          this.toggleDiscussionBtn.removeClass('shown');
          this.toggleDiscussionBtn.find('.button-text').html("Show Discussion");
          return this.showed = false;
        } else {
          this.toggleDiscussionBtn.addClass('shown');
          this.toggleDiscussionBtn.find('.button-text').html("Hide Discussion");
          if (this.retrieved) {
            this.$("section.discussion").slideDown();
            return this.showed = true;
          } else {
            $elem = this.toggleDiscussionBtn;
            return this.loadPage($elem);
          }
        }
      };

      DiscussionModuleView.prototype.loadPage = function($elem) {
        var discussionId, url,
          _this = this;
        discussionId = this.$el.data("discussion-id");
        url = DiscussionUtil.urlFor('retrieve_discussion', discussionId) + ("?page=" + this.page);
        return DiscussionUtil.safeAjax({
          $elem: $elem,
          $loading: $elem,
          url: url,
          type: "GET",
          dataType: 'json',
          success: function(response, textStatus, jqXHR) {
            return _this.renderDiscussion($elem, response, textStatus, discussionId);
          }
        });
      };

      DiscussionModuleView.prototype.renderDiscussion = function($elem, response, textStatus, discussionId) {
        var $discussion, allow_anonymous, allow_anonymous_to_peers, cohorts, source;
        window.user = new DiscussionUser(response.user_info);
        Content.loadContentInfos(response.annotated_content_info);
        DiscussionUtil.loadRoles(response.roles);
        allow_anonymous = response.allow_anonymous;
        allow_anonymous_to_peers = response.allow_anonymous_to_peers;
        cohorts = response.cohorts;
        this.discussion = new Discussion();
        this.discussion.reset(response.discussion_data, {
          silent: false
        });
        if (response.is_cohorted && response.is_moderator) {
          source = "script#_inline_discussion_cohorted";
        } else {
          source = "script#_inline_discussion";
        }
        $discussion = $(Mustache.render($(source).html(), {
          'threads': response.discussion_data,
          'discussionId': discussionId,
          'allow_anonymous_to_peers': allow_anonymous_to_peers,
          'allow_anonymous': allow_anonymous,
          'cohorts': cohorts
        }));
        if (this.$('section.discussion').length) {
          this.$('section.discussion').replaceWith($discussion);
        } else {
          this.$el.append($discussion);
        }
        this.newPostForm = $('.new-post-article');
        this.threadviews = this.discussion.map(function(thread) {
          return new DiscussionThreadInlineView({
            el: this.$("article#thread_" + thread.id),
            model: thread
          });
        });
        _.each(this.threadviews, function(dtv) {
          return dtv.render();
        });
        DiscussionUtil.bulkUpdateContentInfo(window.$$annotated_content_info);
        this.newPostView = new NewPostInlineView({
          el: this.$('.new-post-article'),
          collection: this.discussion
        });
        this.discussion.on("add", this.addThread);
        this.retrieved = true;
        this.showed = true;
        this.renderPagination(2, response.num_pages);
        if (this.isWaitingOnNewPost) {
          return this.newPostForm.show();
        }
      };

      DiscussionModuleView.prototype.addThread = function(thread, collection, options) {
        var article, threadView;
        article = $("<article class='discussion-thread' id='thread_" + thread.id + "'></article>");
        this.$('section.discussion > .threads').prepend(article);
        threadView = new DiscussionThreadInlineView({
          el: article,
          model: thread
        });
        threadView.render();
        return this.threadviews.unshift(threadView);
      };

      DiscussionModuleView.prototype.renderPagination = function(delta, numPages) {
        var maxPage, minPage, pageUrl, params, thing;
        minPage = Math.max(this.page - delta, 1);
        maxPage = Math.min(this.page + delta, numPages);
        pageUrl = function(number) {
          return "?discussion_page=" + number;
        };
        params = {
          page: this.page,
          lowPages: _.range(minPage, this.page).map(function(n) {
            return {
              number: n,
              url: pageUrl(n)
            };
          }),
          highPages: _.range(this.page + 1, maxPage + 1).map(function(n) {
            return {
              number: n,
              url: pageUrl(n)
            };
          }),
          previous: this.page - 1 >= 1 ? {
            url: pageUrl(this.page - 1),
            number: this.page - 1
          } : false,
          next: this.page + 1 <= numPages ? {
            url: pageUrl(this.page + 1),
            number: this.page + 1
          } : false,
          leftdots: minPage > 2,
          rightdots: maxPage < numPages - 1,
          first: minPage > 1 ? {
            url: pageUrl(1)
          } : false,
          last: maxPage < numPages ? {
            number: numPages,
            url: pageUrl(numPages)
          } : false
        };
        thing = Mustache.render(this.paginationTemplate(), params);
        return this.$('section.pagination').html(thing);
      };

      DiscussionModuleView.prototype.navigateToPage = function(event) {
        event.preventDefault();
        window.history.pushState({}, window.document.title, event.target.href);
        this.page = $(event.target).data('page-number');
        return this.loadPage($(event.target));
      };

      return DiscussionModuleView;

    })(Backbone.View);
  }

}).call(this);
